### ISSUE TITLE
Does not work when used with caprover

### ISSUE THREAD

**Issue by Rhys-Woolcott** [emcniece/DockerYourXyzzy#21] opened 2021-03-19 20:27 UTC
I am unable to use this with Caprover. I have no other way or building, please fix.

Build Logs:
![i](https://i.imgur.com/RNHlznF.png)

Console:
![i](https://i.imgur.com/IJdAGVK.png)

View when using port 8080:
![i](https://i.imgur.com/7s29MRN.png)

View from 80/443:
![image](https://user-images.githubusercontent.com/39465405/111838489-4d481e80-88f1-11eb-9838-bf18c694546c.png)

Here is the links used: [C.GALACTIX.XYZ](https://c.galactix.xyz) [CARDS.CAP.GALACTIX.XYZ](https://cards.cap.galactix.xyz)

EDIT:
note it works on my local machine

**Comment by emcniece** [comment] 2021-03-19 21:30
This appears to be a networking/routing issue which is outside of the scope of this project. Some folks (myself included) have been able to set up reverse proxies like Nginx and Traefik successfully, so we know the problem is not with the container itself.

Closing for now. If the issue persists perhaps you could seek help in CapRover forums!

**Closed as completed by emcniece** 2021-03-19 21:30 UTC
